import org.junit.After;
import org.junit.Before;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class C_DataCob_CadastrarParAcordo {
	WebDriver driver;
	Variaveis_C_Parametros_Acordo acordo;
	Variáveis_Login login;
	_Page_Menu_Superior menu;
	_Page_Menu_Parametros subMenu;
	
	@Before
	public void iniciarSistema() throws InterruptedException {
		driver = new FirefoxDriver();
		acordo = new Variaveis_C_Parametros_Acordo (driver);
		login = new Variáveis_Login (driver);
		menu = new _Page_Menu_Superior (driver);
		subMenu = new _Page_Menu_Parametros (driver);
		
		login.login();
		menu.clicarParametros();
		menu.clicarVisualizarParâmetros();	
		acordo.esperarId("cadastra");
		subMenu.clicarMenuOpções();
		subMenu.clicarSubMenuCálculo();
		subMenu.clicarSubMenuAcordo();
	}

	@After
	public void fecharNavegador() {
		driver.quit();
	}

	@Test
	public void A_Cadastrar_Novo_Parametro_Acordo() throws InterruptedException {
		acordo.esperarId("btnCadastrar");
		acordo.clicarBotãoCadastra("btnCadastrar");
		acordo.esperarId("inputPadrao");
		acordo.inserirDescrição("inputPadrao", acordo.descricao);
		acordo.clicarBaixaProporcional("baixaProporcional");
		acordo.desmarcarIgnorarCancelamentoAcordoAutomatico("ignorarCancelarAcordo");
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
	}
	
	@Test
	public void B_Inserir_Parametro_Sem_Renegociacao() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarId("adcionaTipo");
		acordo.clicarAbaTipo("#targets > ul:nth-child(1) > li:nth-child(1)");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adcionaTipo");
		acordo.esperarId("dtInicio");
		acordo.clicarFlagAtivo("ativo");
		acordo.inserirDescrição("descricao", acordo.descricaoSemRenegociação);
		acordo.inserirDataInicio("dtInicio", acordo.dataInicio);
		acordo.inserirDataFim("dtFim", acordo.dataFim);
		acordo.clicarNormal("normal");
		acordo.clicarBoletagem("ckboletagem");
		acordo.clicarAPI("ckUsoApi");
		acordo.clicarDataPact("ckdatapact");
		acordo.clicarWebService("ckusawebserivce");
		acordo.clicarCobrarJurosAtraso("cobrarJurosAtraso");
		acordo.nãoClicarRenegociação("ckRenegociacao");
		acordo.nãoClicarConfirmarDadosCadastrais("ckConfirmarDadosCadastrais");
		acordo.clicarLinear("jurosLinear");
		acordo.inserirDiasGraçaAtraso("diasGracaAtraso", acordo.diasGraça);
		acordo.inserirJurosAtraso("percJurosAtraso", acordo.jurosAtraso);
		acordo.inserirStandbyAcordo("diasStadbyAcordo", acordo.diasStandby);
		acordo.inserirCancelamentoAcordo1Parcela("diasCancelamentoAcordo1Parc", acordo.cancelarAcordo1parcela);
		acordo.inserirCancelamentoAcordo2Parcela("diasCancelamentoAcordo2Parc", acordo.cancelarAcordo2parcela);
		acordo.nãoClicarNãoCancelar2Parcela("cbBloquearSegundoCancelamento");
		acordo.inserirReenvioBoleto1Parcela("diasReenvio1Parc", acordo.reenvioBoleto1parcela);
		acordo.inserirReenvioBoleto2Parcela("diasReenvio2Parc", acordo.reenvioBoleto2parcela);
		acordo.inserirValorPrestaçãoMínima("vlPrestacaoMinimo", acordo.valorPrestacaoMinima);
		acordo.limparCódigoPolítica("codPolitica");
		acordo.clicarMaisAntiga("antiga");
		acordo.clicarEnquadramentoVencimento("vencimento");
		acordo.clicarVencimentoDiaUtil("parcDiaUtil");
		acordo.clicarEntradaMaior("chkParcelaEntrada");
		acordo.nãoClicarEntradaIgualParcela("chkParcelaEntrada");
		acordo.nãoClicarProjerar1Parcela("permitirProjetarVencimento1Parcela");
		acordo.nãoClicarLiquidaAcordo("checkDevolveParcelas");
		acordo.nãoClicarAcordoForaAlçada("checkbloquearalcada");
		acordo.nãoClicarNegociaçãoForaAlçada("checkbloquearnegociacaoalcada");
		acordo.nãoClicarProrrogação("checkdtprorrogacao");
		acordo.clicarIgnorarDescontoPC("checkignorarpc");
		acordo.clicarHonorário1Parcela("checkHonorarioPrimeiraParcela");
		acordo.selecionarTermoAcordo("cbtermoacordo", "Selecionar");
		acordo.selecionarTermoDataPact("cbCartaWordDataPact", "Selecionar");
		acordo.clicarSalvar("confirmaTipo");
		acordo.esperarCssSelector(".barra_top");
		String mensagemSucesso = acordo.mensagem(".barra_top");
		acordo.validarMensagem("Atenção", mensagemSucesso);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}
	
	@Test
	public void C_Inserir_Parametro_Com_Renegociacao() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarId("adcionaTipo");
		acordo.clicarAbaTipo("#targets > ul:nth-child(1) > li:nth-child(1)");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adcionaTipo");
		acordo.esperarId("dtInicio");
		acordo.clicarFlagAtivo("ativo");
		acordo.inserirDescrição("descricao", acordo.descricaoRenegociação);
		acordo.inserirDataInicio("dtInicio", acordo.dataInicio);
		acordo.inserirDataFim("dtFim", acordo.dataFim);
		acordo.clicarNormal("normal");
		acordo.clicarBoletagem("ckboletagem");
		acordo.clicarAPI("ckUsoApi");
		acordo.clicarDataPact("ckdatapact");
		acordo.clicarWebService("ckusawebserivce");
		acordo.clicarCobrarJurosAtraso("cobrarJurosAtraso");
		acordo.clicarRenegociação("ckRenegociacao");
		acordo.nãoClicarConfirmarDadosCadastrais("ckConfirmarDadosCadastrais");
		acordo.clicarLinear("jurosLinear");
		acordo.inserirDiasGraçaAtraso("diasGracaAtraso", acordo.diasGraça);
		acordo.inserirJurosAtraso("percJurosAtraso", acordo.jurosAtraso);
		acordo.inserirStandbyAcordo("diasStadbyAcordo", acordo.diasStandby);
		acordo.inserirCancelamentoAcordo1Parcela("diasCancelamentoAcordo1Parc", acordo.cancelarAcordo1parcela);
		acordo.inserirCancelamentoAcordo2Parcela("diasCancelamentoAcordo2Parc", acordo.cancelarAcordo2parcela);
		acordo.nãoClicarNãoCancelar2Parcela("cbBloquearSegundoCancelamento");
		acordo.inserirReenvioBoleto1Parcela("diasReenvio1Parc", acordo.reenvioBoleto1parcela);
		acordo.inserirReenvioBoleto2Parcela("diasReenvio2Parc", acordo.reenvioBoleto2parcela);
		acordo.inserirValorPrestaçãoMínima("vlPrestacaoMinimo", acordo.valorPrestacaoMinima);
		acordo.limparCódigoPolítica("codPolitica");
		acordo.clicarMaisAntiga("antiga");
		acordo.clicarEnquadramentoVencimento("vencimento");
		acordo.clicarVencimentoDiaUtil("parcDiaUtil");
		acordo.clicarEntradaMaior("chkParcelaEntrada");
		acordo.nãoClicarEntradaIgualParcela("chkParcelaEntrada");
		acordo.nãoClicarProjerar1Parcela("permitirProjetarVencimento1Parcela");
		acordo.nãoClicarLiquidaAcordo("checkDevolveParcelas");
		acordo.nãoClicarAcordoForaAlçada("checkbloquearalcada");
		acordo.nãoClicarNegociaçãoForaAlçada("checkbloquearnegociacaoalcada");
		acordo.nãoClicarProrrogação("checkdtprorrogacao");
		acordo.clicarIgnorarDescontoPC("checkignorarpc");
		acordo.clicarHonorário1Parcela("checkHonorarioPrimeiraParcela");
		acordo.selecionarTermoAcordo("cbtermoacordo", "Selecionar");
		acordo.selecionarTermoDataPact("cbCartaWordDataPact", "Selecionar");
		acordo.clicarSalvar("confirmaTipo");
		acordo.esperarCssSelector(".barra_top");
		String mensagemSucesso = acordo.mensagem(".barra_top");
		acordo.validarMensagem("Atenção", mensagemSucesso);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}
	
	@Test
	public void D_Inserir_Parametro_Faltando_Informações() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarId("adcionaTipo");
		acordo.clicarAbaTipo("#targets > ul:nth-child(1) > li:nth-child(1)");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adcionaTipo");
		acordo.esperarId("dtInicio");
		acordo.clicarFlagAtivo("ativo");
		acordo.inserirDataFim("dtFim", acordo.dataFim);
		acordo.clicarNormal("normal");
		acordo.clicarBoletagem("ckboletagem");
		acordo.clicarAPI("ckUsoApi");
		acordo.clicarDataPact("ckdatapact");
		acordo.clicarWebService("ckusawebserivce");
		acordo.clicarCobrarJurosAtraso("cobrarJurosAtraso");
		acordo.clicarRenegociação("ckRenegociacao");
		acordo.nãoClicarConfirmarDadosCadastrais("ckConfirmarDadosCadastrais");
		acordo.clicarLinear("jurosLinear");
		acordo.inserirDiasGraçaAtraso("diasGracaAtraso", acordo.diasGraça);
		acordo.inserirJurosAtraso("percJurosAtraso", acordo.jurosAtraso);
		acordo.inserirCancelamentoAcordo1Parcela("diasCancelamentoAcordo1Parc", acordo.cancelarAcordo1parcela);
		acordo.inserirCancelamentoAcordo2Parcela("diasCancelamentoAcordo2Parc", acordo.cancelarAcordo2parcela);
		acordo.nãoClicarNãoCancelar2Parcela("cbBloquearSegundoCancelamento");
		acordo.inserirReenvioBoleto1Parcela("diasReenvio1Parc", acordo.reenvioBoleto1parcela);
		acordo.inserirReenvioBoleto2Parcela("diasReenvio2Parc", acordo.reenvioBoleto2parcela);
		acordo.inserirValorPrestaçãoMínima("vlPrestacaoMinimo", acordo.valorPrestacaoMinima);
		acordo.limparCódigoPolítica("codPolitica");
		acordo.clicarMaisAntiga("antiga");
		acordo.clicarEnquadramentoVencimento("vencimento");
		acordo.clicarVencimentoDiaUtil("parcDiaUtil");
		acordo.clicarEntradaMaior("chkParcelaEntrada");
		acordo.nãoClicarEntradaIgualParcela("chkParcelaEntrada");
		acordo.nãoClicarProjerar1Parcela("permitirProjetarVencimento1Parcela");
		acordo.nãoClicarLiquidaAcordo("checkDevolveParcelas");
		acordo.nãoClicarAcordoForaAlçada("checkbloquearalcada");
		acordo.nãoClicarNegociaçãoForaAlçada("checkbloquearnegociacaoalcada");
		acordo.nãoClicarProrrogação("checkdtprorrogacao");
		acordo.clicarIgnorarDescontoPC("checkignorarpc");
		acordo.clicarHonorário1Parcela("checkHonorarioPrimeiraParcela");
		acordo.selecionarTermoAcordo("cbtermoacordo", "Selecionar");
		acordo.selecionarTermoDataPact("cbCartaWordDataPact", "Selecionar");
		acordo.clicarSalvar("confirmaTipo");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemErro = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Preencha os campos destacados.", mensagemErro);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}
	
	@Test
	public void E_Inserir_Config_AVista_Sem_Renegociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe0);
		acordo.inserirDiasAte("ateVista", acordo.diasAte30);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe31);
		acordo.inserirDiasAte("ateVista", acordo.diasAte60);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista1);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal1);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal1);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe61);
		acordo.inserirDiasAte("ateVista", acordo.diasAte90);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista2);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal2);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal2);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe91);
		acordo.inserirDiasAte("ateVista", acordo.diasAte9999999);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista3);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal3);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal3);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}

	@Test 
	public void I_Inserir_Config_AVista_Renegociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe0);
		acordo.inserirDiasAte("ateVista", acordo.diasAte30);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe31);
		acordo.inserirDiasAte("ateVista", acordo.diasAte60);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista1);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal1);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal1);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	
			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe61);
		acordo.inserirDiasAte("ateVista", acordo.diasAte90);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista2);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal2);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal2);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	
			Thread.sleep(1300);
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAVista("//*[@id=\"targets\"]/ul/li[2]/a");
			Thread.sleep(1300);
		acordo.clicarBotãoInserir("adicionaFaixaVista");
		acordo.inserirDiasDe("deVista", acordo.diasDe91);
		acordo.inserirDiasAte("ateVista", acordo.diasAte9999999);
		acordo.inserirComissão ("percComissaoAVista", acordo.comissãoAVista3);
		acordo.inserirDescontoComissão("percDescontoCorrecao", acordo.descontoPrincipal3);
		acordo.inserirDescontoPrincipal("percDescontoPrincipal", acordo.descontoPrincipal3);
		acordo.nãoMarcarAcordoPendente("acordoPendenteAVista");
		acordo.nãoMarcarValorMínimo("acordonegociacaominimo");
		acordo.limparCodFaixa("codFaixa");
		acordo.clicarOkID("confirmaFaixaVista");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Adicionado com sucesso.", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}
	
	
	@Test //0 a 30
	public void M_Inserir_Config_APrazo_Negociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe0);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte30);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}

	@Test //31 a 60
	public void N_Inserir_Config_APrazo_Negociação() throws InterruptedException {		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe31);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte60);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
	}
	 
	 @Test //61 a 90
	 public void O_Inserir_Config_APrazo_Negociação() throws InterruptedException {		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe61);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte90);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
	}
	
	@Test //91 a 9999999
	public void P_Inserir_Config_APrazo_Negociação() throws InterruptedException {		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);	
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe91);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte9999999);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
		}	

	@Test //0 a 30
	public void Q_Inserir_Config_APrazo_Sem_Negociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe0);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte30);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe0);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
	}
	
	@Test //31 a 60
	public void R_Inserir_Config_APrazo_Sem_Negociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe31);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte60);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
			
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe31);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
	}
	
	@Test //61 a 90
	public void S_Inserir_Config_APrazo_Sem_Negociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe61);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte90);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe61);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
	}
	
	@Test //91 a 9999999
	public void T_Inserir_Config_APrazo_Sem_Negociação() throws InterruptedException {
		acordo.esperarXpath("//*[@id=\'gridAcordo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetroAcordoCriado(acordo.descricao);
		acordo.clicarBotãoParâmetroAcordo();
		acordo.esperarXpath("//*[@id=\"gridTipo\"]/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaParâmetrosAcordo(acordo.descricaoSemRenegociação);
		acordo.clicarAPrazo("//*[@id=\'targets\']/ul/li[3]/a");
			Thread.sleep(1300);
		acordo.clicarVisualizar ("visualizaPrazo");
		acordo.esperarId("adcionaFaixaPrazo");
		acordo.clicarInserirFaixa("adcionaFaixaPrazo");
		acordo.inserirFaixaDe("dePrazo", acordo.diasDe91);
		acordo.inserirFaixaAte("atePrazo", acordo.diasAte9999999);
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso!", mensagemSucesso);
		acordo.clicarOkXpath("//*[@id=\'msgBoxContent\']/div/div[2]/a");
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe0);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte3);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento1);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin1);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima1);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo1);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP1);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP1);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso1 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso1);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");
		
		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe4);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte6);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento2);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin2);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima2);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo2);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP2);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP2);
		acordo.nãoClicarAcordoPendente ("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso2 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso2);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe7);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte9);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento3);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin3);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima3);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo3);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP3);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP3);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso3 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso3);
		acordo.clicarOkcss(".caixa_bottom > a:nth-child(1)");

		acordo.esperarXpath("//*[@id=\'gridFaixaPrazo\']/table/tbody/tr[2]/td/div/div/table/tbody/tr[2]");
		acordo.tabelaFaixasAtraso(acordo.diasDe91);
		acordo.clicarInserirConfigParcelamento("adcionaFaixaParcelamento");
		acordo.esperarId("deParcelamento");
		acordo.inserirParcelaDe("deParcelamento", acordo.parcelaDe10);
		acordo.inserirParcelaAte("ateParcelamento", acordo.parcelaAte12);
		acordo.inserirPorcentoParcelamento("percParcelamento", acordo.parcelamento4);
		acordo.inserirPorcentoEntMinima("percEntradaMini", acordo.porcEntradaMin4);
		acordo.inserirEntradaMinima("vlEntradaMini", acordo.entradaMinima4);
		acordo.inserirPorcentoComissão("percComissaoAPrazo", acordo.comissaoPrazo4);
		acordo.inserirPorcentoDescPrincipal("percDescontoPrincipalAPrazo", acordo.descPrincipalP4);
		acordo.inserirPorcentoDescCorreção("percDescontoCorrecaoAPrazo", acordo.descCorrecaoP4);
		acordo.nãoClicarAcordoPendente("acordoPendente");
		acordo.clicarConfirmar("//*[@id=\'msgBoxContent\']/div/div[2]/a[2]");
		acordo.esperarCssSelector(".textoAlerta");
		String mensagemSucesso4 = acordo.mensagem(".textoAlerta");
		acordo.validarMensagem("Inserido com sucesso", mensagemSucesso4);
	}
}
